export const ROLES = {
  MORADOR: "MORADOR",
  AGENTE: "AGENTE",
  GESTOR: "GESTOR",
  ONG: "ONG",
  PARCEIRO: "PARCEIRO",
  ADMIN: "ADMIN",
};

export const SYSTEM_ROLES = [ROLES.AGENTE, ROLES.GESTOR, ROLES.ONG, ROLES.PARCEIRO, ROLES.ADMIN];
